// <auto-generated />
namespace Lab_BigSchool_TranThanhPhong.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initprogress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initprogress));
        
        string IMigrationMetadata.Id
        {
            get { return "202205300129187_init progress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
